name: Morse Testing with Pytest
run-name: Pytest
on:
  push:
    branches:
      - main
      - 'releases/**' # Filters to run only when a push to a branch that matches the branches filter occurs
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and generate XML report
      run: pytest --junitxml=pytest-report.xml
      continue-on-error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: pytest-report.xml

    - name: Notify on success
      if: success()
      run: echo "Tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Tests failed"
